# Actual environment
spring:
  profiles.actives: dev

---

# Dev Profile
spring:
  profiles: dev
  datasource:
    platform: postgres
    url: jdbc:postgresql://${postgres.hostname:localhost}:${postgres.port:5432}/wallet
    driver-class-name: org.postgresql.Driver
    username: ${postgres.user:postgres}
    password: ${postgres.password:fpf@1212}
    validation-query: SELECT 1
    test-on-borrow: true
    initial-size: 3
    max-active: 5
  jpa:
    database: postgresql
    show-sql: ${postgres.show_sql:true}
    open-in-view: false
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: true
      hibernate.hbm2ddl.auto: update
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
---

spring:
  profiles: test
  datasource:
    platform: postgres
    url: jdbc:postgresql://${postgres.hostname:localhost}:${postgres.port:5432}/wallet-test
    driver-class-name: org.postgresql.Driver
    username: ${postgres.user:postgres}
    password: ${postgres.password:fpf@1212}
    validation-query: SELECT 1
    test-on-borrow: true
    initial-size: 3
    max-active: 5
  jpa:
    database: postgresql
    show-sql: ${postgres.show_sql:true}
    open-in-view: false
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: true
      hibernate.hbm2ddl.auto: update
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect