/*
 * This file is generated by jOOQ.
*/
package br.com.nalone.jooqpoc.core.domain.jooq;


import br.com.nalone.jooqpoc.core.domain.jooq.tables.TbAsset;
import br.com.nalone.jooqpoc.core.domain.jooq.tables.TbCotation;
import br.com.nalone.jooqpoc.core.domain.jooq.tables.TbInvestor;
import br.com.nalone.jooqpoc.core.domain.jooq.tables.TbWallet;
import br.com.nalone.jooqpoc.core.domain.jooq.tables.records.TbAssetRecord;
import br.com.nalone.jooqpoc.core.domain.jooq.tables.records.TbCotationRecord;
import br.com.nalone.jooqpoc.core.domain.jooq.tables.records.TbInvestorRecord;
import br.com.nalone.jooqpoc.core.domain.jooq.tables.records.TbWalletRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>public</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<TbAssetRecord> TB_ASSET_PKEY = UniqueKeys0.TB_ASSET_PKEY;
    public static final UniqueKey<TbCotationRecord> TB_COTATION_PKEY = UniqueKeys0.TB_COTATION_PKEY;
    public static final UniqueKey<TbInvestorRecord> TB_INVESTOR_PKEY = UniqueKeys0.TB_INVESTOR_PKEY;
    public static final UniqueKey<TbWalletRecord> TB_WALLET_PKEY = UniqueKeys0.TB_WALLET_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<TbAssetRecord, TbWalletRecord> TB_ASSET__FKDXK8WDQCCACGWMFDPWH2BUQB = ForeignKeys0.TB_ASSET__FKDXK8WDQCCACGWMFDPWH2BUQB;
    public static final ForeignKey<TbCotationRecord, TbAssetRecord> TB_COTATION__FK3N00T1H371KFIX62QH738PFAV = ForeignKeys0.TB_COTATION__FK3N00T1H371KFIX62QH738PFAV;
    public static final ForeignKey<TbWalletRecord, TbInvestorRecord> TB_WALLET__FK1JUP0RG1U7M8UUVC0OOO2WBSA = ForeignKeys0.TB_WALLET__FK1JUP0RG1U7M8UUVC0OOO2WBSA;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<TbAssetRecord> TB_ASSET_PKEY = createUniqueKey(TbAsset.TB_ASSET, "tb_asset_pkey", TbAsset.TB_ASSET.ID_ASSET);
        public static final UniqueKey<TbCotationRecord> TB_COTATION_PKEY = createUniqueKey(TbCotation.TB_COTATION, "tb_cotation_pkey", TbCotation.TB_COTATION.ID_COTATION);
        public static final UniqueKey<TbInvestorRecord> TB_INVESTOR_PKEY = createUniqueKey(TbInvestor.TB_INVESTOR, "tb_investor_pkey", TbInvestor.TB_INVESTOR.ID_INVESTOR);
        public static final UniqueKey<TbWalletRecord> TB_WALLET_PKEY = createUniqueKey(TbWallet.TB_WALLET, "tb_wallet_pkey", TbWallet.TB_WALLET.ID_WALLET);
    }

    private static class ForeignKeys0 extends AbstractKeys {
        public static final ForeignKey<TbAssetRecord, TbWalletRecord> TB_ASSET__FKDXK8WDQCCACGWMFDPWH2BUQB = createForeignKey(br.com.nalone.jooqpoc.core.domain.jooq.Keys.TB_WALLET_PKEY, TbAsset.TB_ASSET, "tb_asset__fkdxk8wdqccacgwmfdpwh2buqb", TbAsset.TB_ASSET.ID_WALLET);
        public static final ForeignKey<TbCotationRecord, TbAssetRecord> TB_COTATION__FK3N00T1H371KFIX62QH738PFAV = createForeignKey(br.com.nalone.jooqpoc.core.domain.jooq.Keys.TB_ASSET_PKEY, TbCotation.TB_COTATION, "tb_cotation__fk3n00t1h371kfix62qh738pfav", TbCotation.TB_COTATION.ID_ASSET);
        public static final ForeignKey<TbWalletRecord, TbInvestorRecord> TB_WALLET__FK1JUP0RG1U7M8UUVC0OOO2WBSA = createForeignKey(br.com.nalone.jooqpoc.core.domain.jooq.Keys.TB_INVESTOR_PKEY, TbWallet.TB_WALLET, "tb_wallet__fk1jup0rg1u7m8uuvc0ooo2wbsa", TbWallet.TB_WALLET.ID_INVESTOR);
    }
}
