/*
 * This file is generated by jOOQ.
*/
package br.com.nalone.jooqpoc.core.domain.jooq;


import br.com.nalone.jooqpoc.core.domain.jooq.tables.TbAsset;
import br.com.nalone.jooqpoc.core.domain.jooq.tables.TbCotation;
import br.com.nalone.jooqpoc.core.domain.jooq.tables.TbInvestor;
import br.com.nalone.jooqpoc.core.domain.jooq.tables.TbWallet;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = -203708261;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.tb_asset</code>.
     */
    public final TbAsset TB_ASSET = br.com.nalone.jooqpoc.core.domain.jooq.tables.TbAsset.TB_ASSET;

    /**
     * The table <code>public.tb_cotation</code>.
     */
    public final TbCotation TB_COTATION = br.com.nalone.jooqpoc.core.domain.jooq.tables.TbCotation.TB_COTATION;

    /**
     * The table <code>public.tb_investor</code>.
     */
    public final TbInvestor TB_INVESTOR = br.com.nalone.jooqpoc.core.domain.jooq.tables.TbInvestor.TB_INVESTOR;

    /**
     * The table <code>public.tb_wallet</code>.
     */
    public final TbWallet TB_WALLET = br.com.nalone.jooqpoc.core.domain.jooq.tables.TbWallet.TB_WALLET;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.ASSET_ID_ASSET_SEQ,
            Sequences.COTATION_ID_COTATION_SEQ,
            Sequences.INVESTOR_ID_INVESTOR_SEQ,
            Sequences.WALLET_ID_WALLET_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            TbAsset.TB_ASSET,
            TbCotation.TB_COTATION,
            TbInvestor.TB_INVESTOR,
            TbWallet.TB_WALLET);
    }
}
