/*
 * This file is generated by jOOQ.
*/
package br.com.nalone.jooqpoc.core.domain.jooq;


import br.com.nalone.jooqpoc.core.domain.jooq.tables.TbAsset;
import br.com.nalone.jooqpoc.core.domain.jooq.tables.TbCotation;
import br.com.nalone.jooqpoc.core.domain.jooq.tables.TbInvestor;
import br.com.nalone.jooqpoc.core.domain.jooq.tables.TbWallet;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.tb_asset</code>.
     */
    public static final TbAsset TB_ASSET = br.com.nalone.jooqpoc.core.domain.jooq.tables.TbAsset.TB_ASSET;

    /**
     * The table <code>public.tb_cotation</code>.
     */
    public static final TbCotation TB_COTATION = br.com.nalone.jooqpoc.core.domain.jooq.tables.TbCotation.TB_COTATION;

    /**
     * The table <code>public.tb_investor</code>.
     */
    public static final TbInvestor TB_INVESTOR = br.com.nalone.jooqpoc.core.domain.jooq.tables.TbInvestor.TB_INVESTOR;

    /**
     * The table <code>public.tb_wallet</code>.
     */
    public static final TbWallet TB_WALLET = br.com.nalone.jooqpoc.core.domain.jooq.tables.TbWallet.TB_WALLET;
}
