/*
 * This file is generated by jOOQ.
*/
package br.com.nalone.jooqpoc.core.domain.jooq.tables;


import br.com.nalone.jooqpoc.core.domain.jooq.Keys;
import br.com.nalone.jooqpoc.core.domain.jooq.Public;
import br.com.nalone.jooqpoc.core.domain.jooq.tables.records.TbWalletRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TbWallet extends TableImpl<TbWalletRecord> {

    private static final long serialVersionUID = 1806981809;

    /**
     * The reference instance of <code>public.tb_wallet</code>
     */
    public static final TbWallet TB_WALLET = new TbWallet();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TbWalletRecord> getRecordType() {
        return TbWalletRecord.class;
    }

    /**
     * The column <code>public.tb_wallet.id_wallet</code>.
     */
    public final TableField<TbWalletRecord, Long> ID_WALLET = createField("id_wallet", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.tb_wallet.tx_description</code>.
     */
    public final TableField<TbWalletRecord, String> TX_DESCRIPTION = createField("tx_description", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

    /**
     * The column <code>public.tb_wallet.tx_name</code>.
     */
    public final TableField<TbWalletRecord, String> TX_NAME = createField("tx_name", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

    /**
     * The column <code>public.tb_wallet.id_investor</code>.
     */
    public final TableField<TbWalletRecord, Long> ID_INVESTOR = createField("id_investor", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * Create a <code>public.tb_wallet</code> table reference
     */
    public TbWallet() {
        this("tb_wallet", null);
    }

    /**
     * Create an aliased <code>public.tb_wallet</code> table reference
     */
    public TbWallet(String alias) {
        this(alias, TB_WALLET);
    }

    private TbWallet(String alias, Table<TbWalletRecord> aliased) {
        this(alias, aliased, null);
    }

    private TbWallet(String alias, Table<TbWalletRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TbWalletRecord> getPrimaryKey() {
        return Keys.TB_WALLET_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TbWalletRecord>> getKeys() {
        return Arrays.<UniqueKey<TbWalletRecord>>asList(Keys.TB_WALLET_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<TbWalletRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<TbWalletRecord, ?>>asList(Keys.TB_WALLET__FK1JUP0RG1U7M8UUVC0OOO2WBSA);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbWallet as(String alias) {
        return new TbWallet(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TbWallet rename(String name) {
        return new TbWallet(name, null);
    }
}
