/*
 * This file is generated by jOOQ.
*/
package br.com.nalone.jooqpoc.core.domain.jooq.tables.records;


import br.com.nalone.jooqpoc.core.domain.jooq.tables.TbAsset;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TbAssetRecord extends UpdatableRecordImpl<TbAssetRecord> implements Record6<Long, String, String, String, Timestamp, Long> {

    private static final long serialVersionUID = 333047601;

    /**
     * Setter for <code>public.tb_asset.id_asset</code>.
     */
    public void setIdAsset(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.tb_asset.id_asset</code>.
     */
    public Long getIdAsset() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.tb_asset.tx_acronym</code>.
     */
    public void setTxAcronym(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.tb_asset.tx_acronym</code>.
     */
    public String getTxAcronym() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.tb_asset.tx_description</code>.
     */
    public void setTxDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.tb_asset.tx_description</code>.
     */
    public String getTxDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.tb_asset.tx_name</code>.
     */
    public void setTxName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.tb_asset.tx_name</code>.
     */
    public String getTxName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.tb_asset.dt_wallet_date</code>.
     */
    public void setDtWalletDate(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.tb_asset.dt_wallet_date</code>.
     */
    public Timestamp getDtWalletDate() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>public.tb_asset.id_wallet</code>.
     */
    public void setIdWallet(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.tb_asset.id_wallet</code>.
     */
    public Long getIdWallet() {
        return (Long) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Long, String, String, String, Timestamp, Long> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Long, String, String, String, Timestamp, Long> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return TbAsset.TB_ASSET.ID_ASSET;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TbAsset.TB_ASSET.TX_ACRONYM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TbAsset.TB_ASSET.TX_DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TbAsset.TB_ASSET.TX_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return TbAsset.TB_ASSET.DT_WALLET_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field6() {
        return TbAsset.TB_ASSET.ID_WALLET;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getIdAsset();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getTxAcronym();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getTxDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getTxName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getDtWalletDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value6() {
        return getIdWallet();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbAssetRecord value1(Long value) {
        setIdAsset(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbAssetRecord value2(String value) {
        setTxAcronym(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbAssetRecord value3(String value) {
        setTxDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbAssetRecord value4(String value) {
        setTxName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbAssetRecord value5(Timestamp value) {
        setDtWalletDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbAssetRecord value6(Long value) {
        setIdWallet(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbAssetRecord values(Long value1, String value2, String value3, String value4, Timestamp value5, Long value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TbAssetRecord
     */
    public TbAssetRecord() {
        super(TbAsset.TB_ASSET);
    }

    /**
     * Create a detached, initialised TbAssetRecord
     */
    public TbAssetRecord(Long idAsset, String txAcronym, String txDescription, String txName, Timestamp dtWalletDate, Long idWallet) {
        super(TbAsset.TB_ASSET);

        set(0, idAsset);
        set(1, txAcronym);
        set(2, txDescription);
        set(3, txName);
        set(4, dtWalletDate);
        set(5, idWallet);
    }
}
