/*
 * This file is generated by jOOQ.
*/
package br.com.nalone.jooqpoc.core.domain.jooq.tables.records;


import br.com.nalone.jooqpoc.core.domain.jooq.tables.TbInvestor;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TbInvestorRecord extends UpdatableRecordImpl<TbInvestorRecord> implements Record5<Long, String, String, String, String> {

    private static final long serialVersionUID = 562446176;

    /**
     * Setter for <code>public.tb_investor.id_investor</code>.
     */
    public void setIdInvestor(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.tb_investor.id_investor</code>.
     */
    public Long getIdInvestor() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.tb_investor.tx_email</code>.
     */
    public void setTxEmail(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.tb_investor.tx_email</code>.
     */
    public String getTxEmail() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.tb_investor.tx_first_name</code>.
     */
    public void setTxFirstName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.tb_investor.tx_first_name</code>.
     */
    public String getTxFirstName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.tb_investor.tx_last_name</code>.
     */
    public void setTxLastName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.tb_investor.tx_last_name</code>.
     */
    public String getTxLastName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.tb_investor.tx_password</code>.
     */
    public void setTxPassword(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.tb_investor.tx_password</code>.
     */
    public String getTxPassword() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, String, String, String, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, String, String, String, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return TbInvestor.TB_INVESTOR.ID_INVESTOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TbInvestor.TB_INVESTOR.TX_EMAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TbInvestor.TB_INVESTOR.TX_FIRST_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TbInvestor.TB_INVESTOR.TX_LAST_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return TbInvestor.TB_INVESTOR.TX_PASSWORD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getIdInvestor();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getTxEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getTxFirstName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getTxLastName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getTxPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbInvestorRecord value1(Long value) {
        setIdInvestor(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbInvestorRecord value2(String value) {
        setTxEmail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbInvestorRecord value3(String value) {
        setTxFirstName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbInvestorRecord value4(String value) {
        setTxLastName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbInvestorRecord value5(String value) {
        setTxPassword(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbInvestorRecord values(Long value1, String value2, String value3, String value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TbInvestorRecord
     */
    public TbInvestorRecord() {
        super(TbInvestor.TB_INVESTOR);
    }

    /**
     * Create a detached, initialised TbInvestorRecord
     */
    public TbInvestorRecord(Long idInvestor, String txEmail, String txFirstName, String txLastName, String txPassword) {
        super(TbInvestor.TB_INVESTOR);

        set(0, idInvestor);
        set(1, txEmail);
        set(2, txFirstName);
        set(3, txLastName);
        set(4, txPassword);
    }
}
